### ISSUE TITLE
Question 1.70

### ISSUE THREAD

**Issue by neilhwang** [jbryer/DATA606Spring2017#10]
Hi Professor Bryer,
For question 1.70 on homework 1, do we need to read the Turnbull paper to get the details on the study, such as the sample size, the size of treatment / control groups, etc? The questions (such as part d.ii) imply that we need these numbers.

Thank you,
Neil

**Comment by neilhwang** [comment]
Hi again, 
Never mind. I see that there is an associated R data file on the textbook's website that we are supposed to use to answer this question. I guess I should look there whenever a dataset or a study is mentioned!
Best,
Neil

**Comment by jbryer** [comment]
I'll make a note about this for the next semester. Thanks.
