### ISSUE TITLE
Homework presentation signup sheet

### ISSUE THREAD

**Issue by neilhwang** [jbryer/DATA606Spring2017#11]
Hi Professor,
The presentation signup sheet appears to be one from last term. Should we delete the entries that are in there now and put in new dates and problems? 

Thank you,
Neil

**Comment by jbryer** [comment]
Please use this link: https://docs.google.com/spreadsheets/d/1geFxr-A0nlhmG36Bd2ftIdYdCZauJJ5xz-Ykq6qI6-M/edit#gid=0

It is also correct on the schedule page: http://data606.net/schedule/
