### ISSUE TITLE
startLab() error in Linux

### ISSUE THREAD

**Issue by neilhwang** [jbryer/DATA606Spring2017#14]
Hello Professor,
I'm using Ubuntu 16.04, and when running startLab('Lab2'), I get the below error:

Error in startLab("Lab2") : 
  The lab did not copy! Not sure why, ask your instructor.
In addition: Warning message:
In file.copy(path, dest_dir, recursive = TRUE, overwrite = FALSE) :
  problem reading directory /home/neilhwang/R/x86_64-pc-linux-gnu-library/3.2/DATA606/Labs/Lab2: No such file or directory

I've downloaded and brought into scope all the packages mentioned in the instructions, so not sure how to address these errors. 

I'd be grateful for any pointers!

Thank you.

**Comment by jbryer** [comment]
Hi @neilhwang Can you try reinstalling the `DATA606` package and let me know if it works. I just pushed what I hope is a fix for this problem.

```
devtools::install_github('jbryer/DATA606')
library(DATA606)
startLab('Lab2')
```
