### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jbrnbrg** [jbryer/DATA606Spring2017#15]
Hi Prof, 

What are the due dates of the project proposal and project?

Kind Regards, 
-Jaan Bernberg

**Comment by jameskuruvilla** [comment]
As per the blackboard, 
Project Proposal is due on  MAR 19, 2017 and Project is due on MAY 18, 2017.  
Thanks
James Kuruvilla

**Comment by jbryer** [comment]
You can also see this page for more information on the project including a sample proposal: http://data606.net/project/

I also discussed the project more on the March 2nd Meetup.
