### ISSUE TITLE
startLab("Lab3") Error

### ISSUE THREAD

**Issue by jameskuruvilla** [jbryer/DATA606Spring2017#16]
Hi Professor,

I installed DATA606 with force=TRUE, loaded library(DATA606), but still I get following error with startLab("Lab3"). Please help

> startLab("Lab3")
      _**Error in startLab("Lab3") : 
      The lab did not copy! Not sure why, ask your instructor.**_

Thanks
James Kuruvilla

**Comment by jbryer** [comment]
Can you tell me if the Lab3 folder and Rmd file were copied over?

**Comment by jameskuruvilla** [comment]
I believe yes. The screenshot is pasted below.

[image: Inline image 1]

**Comment by jbryer** [comment]
I have not forgotten about this issue. Can you email me to see if we can setup a time to do a quick GoToMeeting? I need to be able to see the error on Windows. It seems to not affect all versions of Windows. Thanks.

**Comment by jameskuruvilla** [comment]
Hi Professor,

I am still struggling with similar issues, may be due to my lack of
understanding on how R directory structure works.


Ex: Following commands works well as I execute those individually. But when
I knit it to make html doc. it gives errors

setwd("C:\\Users\\jkuruvilla\\Desktop\\Education\\MS Data Analytics -
CUNY\\Lab4a")
load("more\ames.RData")
area <- ames$Gr.Liv.Area
price <- ames$SalePrice


Can you please let me know your availability to setup a GoToMeeting.
Thanks
James Kuruvilla





I have issues as I run load(). Please let me know your availability to
setup a GoToMeeting.

**Comment by jameskuruvilla** [comment]
I got that resolved. Thanks
