### ISSUE TITLE
Continuous vs. Discrete Variable

### ISSUE THREAD

**Issue by kylegilde** [jbryer/DATA606Spring2017#8]
Hi, Which criteria do you use to determine if a variable is continuous or discrete?
1. The way the data was collected & formatted in the data set gives the impression that it is a discrete variable
2. By its nature, the variable is continuous despite of how it was collected & formatted in the data set

Example 1: a person's age that is collected in whole number years. Continuous or discrete variable?
Example 2:  dollar amounts that do not have any cents. Continuous or discrete variable?
Example 3: a measurement that has been rounded to the tenths place. Continuous or discrete variable?
Example 4: # of candy bars eaten per day. Continuous or discrete variable?
Example 5: # of glasses of water consumed per day. Continuous or discrete variable?

**Comment by jbryer** [comment]
Admittedly this is tricky and will often depend on context. In general, one way to think about the difference is discrete is often something that is counted whereas continuous is something measured. Using that criteria, here is how I would classify your examples:

1. Continuous
2. Continuous
3. Continuous
4. Discrete
5. Discrete
